### PR TITLE
Check for readPreference is wrong

### PR DESCRIPTION
**Pull request by Osterjour**
If none of the values are in it we should throw the error - not the other way around!

### CODE REVIEW

**Comment by Osterjour** [comment]
What about this?

**Comment by mikaelgrave** [comment]
I can't use the latest version of mongojs, or mongo-core-url, because of this readPreference error in parse-mongo-url. Any ETA on merging this pull request? Thanks a lot!

**Comment by tapsboy** [comment]
I am unable to use newer version of promised-mongo as well because of this issue.

**Comment by tapsboy** [comment]
@sorribas Bringing it to your attention

**Comment by sorribas** [comment]
Whoah! My bad on this. Haven't been paying a lot of attention to this repo.

**Comment by sorribas** [comment]
Thanks for the PR. Published as `1.1.1`. Any of you guys would like to become a contributor on the repo so you can merge PRs and publish?

**Comment by tapsboy** [comment]
@sorribas I might be able to help with some of the PRs

**Comment by sorribas** [comment]
@tapsboy added you as a collaborator.

**Pull request merged**
